services:
  db:
    build: ./rideshare-db
    container_name: rideshare-db
    ports:
      - "3306:3306"
    networks:
      - rideshare-net
    healthcheck:
      test: [ "CMD", "mysqladmin", "ping", "-h", "localhost" ]
      interval: 3s
      timeout: 30s
      retries: 10

  app:
    build: ./rideshare-app
    container_name: rideshare-app
    depends_on:
      db:
        condition: service_healthy
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://db:3306/rideshare_db
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: ""
    networks:
      - rideshare-net

networks:
  rideshare-net:
    driver: bridge
