version: '3.8'

services:
  db:
    build: ./carpooling-db
    container_name: swtpCarpooling
    environment:
      MYSQL_DATABASE: swtp_carpooling
      MYSQL_ALLOW_EMPTY_PASSWORD: "true"
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 5s
      timeout: 10s
      retries: 5

  app:
    build: ./carpooling-app
    container_name: carpooling-app
    depends_on:
      db:
        condition: service_healthy
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://db:3306/swtp_carpooling?useSSL=false&allowPublicKeyRetrieval=true
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: ""
    ports:
      - "8080:8080"
    volumes:
      - ./carpooling-app/application.properties:/app/config/application.properties

volumes:
  db_data: